arex:
  api:
    service:
      api: http://arex-report-service:8080
  mongo:
    uri: mongodb://arex:password@mongodb:27017/arex_storage_db
  storage:
    service:
      api: http://arex-storage-service:8080
  schedule:
    service:
      api: http://arex-schedule-service:8080
spring:
  redis:
    host: redis
    port: 6379