server:
  port: 8092
logging:
  config: classpath:log4j2-dev.xml
arex:
  api:
    service:
      api: http://10.118.1.217:18090
  mongo:
    uri: mongodb://arex:password@10.118.1.217:37017/arex_storage_db
  storage:
    service:
      api: http://10.118.1.217:18093
  schedule:
    service:
      api: http://127.0.0.1:8092

spring:
  redis:
    host: 10.118.1.217
    port: 16379