arex:
  api:
    service:
      api: http://arex-report-service:8080
  mongo:
    uri: mongodb://arex:iLoveArex@mongodb:27017/arex_storage_db
  redis:
    uri: redis://redis:6379
  storage:
    service:
      api: http://arex-storage-service:8080