name: Docker SNAPSHOT Image CI

on: push
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: time
        with:
          format: YYYYMMDD-HHmmss
          utcOffset: "+08:00"
      - name: Get Branch Name
        id: tag
        run: |
          FULL_BRANCH_NAME=$GITHUB_REF_NAME
          BRANCH_NAME="${FULL_BRANCH_NAME//\//_}"
          TAG_NAME=${BRANCH_NAME}-${{ steps.time.outputs.formattedTime }}
          echo ${TAG_NAME}
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  docker:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_SNAPSHOT_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SNAPSHOT_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_SNAPSHOT_USERNAME }}/arex-replay-schedule:${{ needs.tag.outputs.tag }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: ${{ vars.ACTION_RESULT_MAIL }}
          # Required sender full name (address can be skipped):
          from: ArexAdmin02 # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully! /n Image tag ${{ needs.tag.outputs.tag }}
